[character] # The name of the module we are configuring is "character"
success_symbol = "[Î»](bold green)"
error_symbol = "[Î»](bold red)"
disabled = true

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'
disabled = true

[git_metrics]
disabled = false

[kubernetes]
disabled = false

[kubernetes.context_aliases]
"faber-aws-dev.*" = "faber-aws-dev"
"faber-aws-int.*" = "faber-aws-int"

[helm]
disabled = true

[gradle]
disabled = true

[java]
disabled = true

[vagrant]
disabled = true

[memory_usage]
format = "running hot $symbol[${ram}( | ${swap})]($style) "
threshold = 70
disabled = false
style = "bold dimmed red"

[shell]
fish_indicator = "ïœ¹"
bash_indicator = "Î»"
powershell_indicator = "â¯_"
unknown_indicator = "mystery shell"
style = "green bold"
disabled = false

# [time]
# disabled = false
# format = 'ğŸ•™[\[ $time \]]($style) '
# use_12hr = true

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "ğŸ”Œ"
discharging_symbol = "âš¡"

[[battery.display]]
threshold = 30
style = "bold red"

[cmd_duration]
min_time = 1_000
format = "took [$duration]($style)"
style = "bold dimmed red"

[directory]
truncation_length = 5
repo_root_style = "bold yellow"
truncation_symbol = "â€¦/"

[git_commit]
commit_hash_length = 8
